### ISSUE TITLE
About Commit

### ISSUE THREAD

**Issue by jihobak** [kaleko/CourseraML#1]
Hello, Thanks for your helps! It's awesome guide to me and really helpful.
If I would like to make suggest or find error, Is it possible to commit? 
If it is possible, How can I commit? just clone & make new branch & commit? 

Thanks

**Comment by jillesme** [comment]
[see this](https://yangsu.github.io/pull-request-tutorial/)!

**Comment by kaleko** [comment]
Hey jiho! Glad you're interested. I am not allowing people to commit to this repository, I want to leave it entirely my work (I made this repository for me, but I'm happy to show it to others). See the response to your question by jillesme for instructions on how to fork the repository to your own repository that you can commit to. Thanks jillesme!

**Comment by jihobak** [comment]
Thanks kaleko~!! I think I find kinds of error in your code. what should I do? May I write it on issue ?

**Comment by kaleko** [comment]
Hey jiho --

Yeah sure if you think you find errors you can let me know on an issue. I can't promise I'll fix them or respond quickly, but I encourage you to let me know!

Thanks,
-kaleko
