### ISSUE TITLE
Logistic Regression - No contour levels were found"

### ISSUE THREAD

**Issue by able-leopard** [kaleko/CourseraML#10]
When running the "def plotBoundary(mytheta, myX, myy, mylambda=0.):"

I got the following error: "contour.py:1173: UserWarning: No contour levels were found within the data range."

Is there a bug in the code or is it a mistake on my side? 

Thanks!

**Comment by kaleko** [comment]
Hey able-lepopard --

I did a fresh clone of the repository, opened ex2.ipynb in a jupyter notebook, and was able to successfully execute all cells with the desired output. The mistake must be on your side, sorry! Maybe try googling the error?

Cheers,
-kaleko

**Comment by able-leopard** [comment]
Alright thanks for the reply! I'll try playing around with it.

Best,
