### ISSUE TITLE
ex_1.py

### ISSUE THREAD

**Issue by jihobak** [kaleko/CourseraML#2]
There is list that name is 'thetahistory' in function 'descendGradient'.

if you print it, you can find out all of element in thetahistory are same.
so graph is like 
![image](https://cloud.githubusercontent.com/assets/10293523/14906997/7b5189d4-0dfd-11e6-8ec1-1d28a572f83c.png)

after change code like 

``` python
thetahistory.append(list(theta[:,0]))
```

![image](https://cloud.githubusercontent.com/assets/10293523/14906944/a8a432fc-0dfc-11e6-95d4-771d824a3e04.png)

therefore, final graph is below
![image](https://cloud.githubusercontent.com/assets/10293523/14907047/33eb453e-0dfe-11e6-8696-12851f5614d4.png)

**Comment by kaleko** [comment]
Good find, Jiho! Fortunately this bug is "minor" because it only affects that 3D visualization (the gradient descent routine still works fine). I have fixed this and pushed it. Thanks!
