### ISSUE TITLE
Hi Kaleko

### ISSUE THREAD

**Issue by wbo4958** [kaleko/CourseraML#4]
Thx for your sharing 

When I review ext1, I have a question about  below code

            tmptheta[j] = theta[j] - (alpha/m)*np.sum((h(initial_theta,X) - y)*np.array(X[:,j]).reshape(m,1))

here why always use **initial_theta**  instead of newest "**theta**"

**Comment by danish-imam** [comment]
**initial_theta** is changing too with each iteration

**Comment by kaleko** [comment]
Thank you wbo4958 for finding this bug. I have fixed it as you suggest. I appreciate your attention to detail, and raising this issue. Thanks!
