### ISSUE TITLE
Request to use portions of code

### ISSUE THREAD

**Issue by doomshead** [kaleko/CourseraML#5]
Hi,

Great work !, 
Im gonna do something on similar lines but less pythonic ,
 the only thing i wanna use are your plot modules (To plot the data as im a noob in matplot lib), 
i will give credits but still do i have your permission to include the portions of your code? 

It would save me a lot of time by doing so . :)

**Comment by kaleko** [comment]
doomshead --

Thanks for asking for permission. Yes you have my permission to use portions of your code. I would appreciate credit in some form; for example, a link to the github repository would be acceptable.

Cheers,
-kaleko
