### ISSUE TITLE
Bug in normalizeRatings function?

### ISSUE THREAD

**Issue by mr-intj** [kaleko/CourseraML#6]
There seems to be a subtle difference between your normalization function and the original Matlab version. As a result, the unrated zeros in `myY` become negative when `Ymean` is subtracted from them.

```
def normalizeRatings(myY, myR):
    ...
    Ymean = np.sum(myY,axis=1)/np.sum(myR,axis=1)  # Unrated elements are ignored here...
    Ymean = Ymean.reshape((Ymean.shape[0],1))

    # ...but not here. The zero elements in myY become negative after subtracting Ymean
    return myY-Ymean, Ymean
```

I think this will yield odd results and possibly prevent convergence. One way to address this would be to also zero out the unrated elements after the subtraction:

```
    return np.multiply(myY-Ymean, myR), Ymean
```

**Comment by kaleko** [comment]
mr-intj --

Thanks for raising this issue. I am not familiar with the original Matlab version, but I would expected the unrated zeros to become negative after subtracting the mean. I do not think this will yield odd results. I refer you to the following link to explain:

https://www.coursera.org/lecture/machine-learning/implementational-detail-mean-normalization-Adk8G

Thanks!
