### ISSUE TITLE
some code need to refine

### ISSUE THREAD

**Issue by kingchenchina** [kaleko/CourseraML#7]
ex1 folder, ex1.ipynb file, the method descentGradient,when compute the tmptheta[j], it should be tmptheta[j] = theta[j] - (alpha/m)*np.sum((h(theta,X)-y)*np.array(X[:,j]).reshape(m,1)), instead of current code tmptheta[j] = theta[j] - (alpha/m)*np.sum((h(**initial_**theta,X)-y)*np.array(X[:,j]).reshape(m,1))

**Comment by kaleko** [comment]
Thank you for finding this, I agree it is a bug. I have fixed it as you suggest and pushed the change. Thank again!
